##### Problem
You want to make a custom transformation to one or more features.
##### Solution
In scikit-learn, use FunctionTransformer to apply a function to a set of features

In [1]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer 

In [2]:
featurs=np.array([[1,2],[3,4],[5,6]])

In [3]:
featurs

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
def add_Ten(x):
    return x+10

In [7]:
add_Ten(featurs)

array([[11, 12],
       [13, 14],
       [15, 16]])

In [8]:
# creat transform
ten_transform=FunctionTransformer(add_Ten)

In [9]:
#Transform freaturs
ten_transform.transform(featurs)

array([[11, 12],
       [13, 14],
       [15, 16]])

### We can create the same transformation in pandas using apply

In [10]:
import pandas as pd

In [11]:
df=pd.DataFrame(featurs , columns=["featurs1","featurs2"])

In [12]:
df

featurs1  featurs2
0         1         2
1         3         4
2         5         6

In [13]:
df.apply(add_Ten)

featurs1  featurs2
0        11        12
1        13        14
2        15        16

In [28]:
# apply methond on only one column
df["featurs1"]=df["featurs1"].apply(add_Ten)

In [29]:
df

featurs1  featurs2
0        21         2
1        23         4
2        25         6